# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nick Lormand
tagline:          Nick Lormand's professional portfolio
description:      ANIMATION/VFX TECHNICAL DIRECTOR
url:              https://nicklormand.com
baseurl:          /

author:
  name:           Nick Lormand
  url:            https://www.linkedin.com/in/nicholas-lormand-331414176

gems:                [jekyll-paginate]
paginate:            5
paginate_path:       page:num

collections:
  experience_posts:
    output: true
    permalink: /work/:path/
    
pagination:
  enabled: true
  per_page: 1
  permalink: '/work/page/:num/'
  title: "Work Page"
  sort_field: 'date'
  sort_reverse: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicklormand/nicklormand_portfolio
