# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Nick Lormand
tagline:          Nick Lormand's professional portfolio
description:      ANIMATION/VFX TECHNICAL DIRECTOR
url:              https://nicklormand.com
baseurl:          /

author:
  name:           Nick Lormand
  url:            https://www.linkedin.com/in/nicholas-lormand-331414176

gems:                [jekyll-paginate]
paginate:            1
paginate_path:       page:num

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nicklormand/nicklormand_portfolio

collections:
  experience_posts:
  posts:

