# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nick Lormand
tagline:          'A Jekyll theme'
description:      'Welcome to my website!'
url:              http://nicklormand.com
baseurl:          /

author:
  name:           'Nick Lormand'
  url:            https://www.linkedin.com/in/nicholas-lormand-331414176/

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/nicklormand
  repo:           https://github.com/nicklormand/portfolio_hyde
